# Generated by Django 6.0.5 on 2026-05-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('eid', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
            ],
        ),
    ]
